import os

# Controls which page is served at /
# Options: "pre-tournament" or "tournament-live"
SITE_MODE = os.environ.get("SITE_MODE", "pre-tournament")

# Google Sheet ID (fill in after creating the sheet)
GOOGLE_SHEET_ID = os.environ.get("GOOGLE_SHEET_ID", "")

# Google Sheet leaderboard embed URL (fill in after publishing the sheet)
LEADERBOARD_EMBED_URL = os.environ.get("LEADERBOARD_EMBED_URL", "")

PLAYERS = [
    {"name": "Scottie Scheffler", "salary": 12400},
    {"name": "Rory McIlroy", "salary": 11100},
    {"name": "Ludvig Aberg", "salary": 10800},
    {"name": "Collin Morikawa", "salary": 10500},
    {"name": "Jon Rahm", "salary": 10400},
    {"name": "Bryson DeChambeau", "salary": 9900},
    {"name": "Xander Schauffele", "salary": 9700},
    {"name": "Justin Thomas", "salary": 9600},
    {"name": "Hideki Matsuyama", "salary": 9500},
    {"name": "Brooks Koepka", "salary": 9400},
    {"name": "Joaquin Niemann", "salary": 9300},
    {"name": "Viktor Hovland", "salary": 9200},
    {"name": "Tommy Fleetwood", "salary": 9100},
    {"name": "Jordan Spieth", "salary": 9000},
    {"name": "Shane Lowry", "salary": 8800},
    {"name": "Patrick Cantlay", "salary": 8700},
    {"name": "Tyrrell Hatton", "salary": 8600},
    {"name": "Min Woo Lee", "salary": 8500},
    {"name": "Russell Henley", "salary": 8400},
    {"name": "Will Zalatoris", "salary": 8300},
    {"name": "Cameron Smith", "salary": 8200},
    {"name": "Akshay Bhatia", "salary": 8100},
    {"name": "Robert Macintyre", "salary": 8000},
    {"name": "Corey Conners", "salary": 7900},
    {"name": "Tony Finau", "salary": 7800},
    {"name": "Wyndham Clark", "salary": 7700},
    {"name": "Sahith Theegala", "salary": 7700},
    {"name": "Jason Day", "salary": 7600},
    {"name": "Sepp Straka", "salary": 7600},
    {"name": "Tom Kim", "salary": 7500},
    {"name": "Dustin Johnson", "salary": 7500},
    {"name": "Sam Burns", "salary": 7400},
    {"name": "Matt Fitzpatrick", "salary": 7400},
    {"name": "Patrick Reed", "salary": 7300},
    {"name": "Sungjae Im", "salary": 7300},
    {"name": "Justin Rose", "salary": 7200},
    {"name": "Adam Scott", "salary": 7200},
    {"name": "Maverick McNealy", "salary": 7100},
    {"name": "Daniel Berger", "salary": 7100},
    {"name": "Sergio Garcia", "salary": 7100},
    {"name": "Davis Thompson", "salary": 7000},
    {"name": "Cameron Young", "salary": 7000},
    {"name": "Keegan Bradley", "salary": 7000},
    {"name": "Thomas Detry", "salary": 6900},
    {"name": "Billy Horschel", "salary": 6900},
    {"name": "Nicolai Hojgaard", "salary": 6900},
    {"name": "J.J. Spaun", "salary": 6800},
    {"name": "Aaron Rai", "salary": 6800},
    {"name": "Brian Harman", "salary": 6800},
    {"name": "Byeong Hun An", "salary": 6800},
    {"name": "Rasmus Hojgaard", "salary": 6700},
    {"name": "Michael Kim", "salary": 6700},
    {"name": "Taylor Pendrith", "salary": 6700},
    {"name": "Phil Mickelson", "salary": 6700},
    {"name": "Cameron Davis", "salary": 6700},
    {"name": "Laurie Canter", "salary": 6600},
    {"name": "Max Greyserman", "salary": 6600},
    {"name": "Lucas Glover", "salary": 6600},
    {"name": "Christiaan Bezuidenhout", "salary": 6600},
    {"name": "Chris Kirk", "salary": 6600},
    {"name": "Max Homa", "salary": 6500},
    {"name": "Nick Dunlap", "salary": 6500},
    {"name": "Harris English", "salary": 6500},
    {"name": "Denny McCarthy", "salary": 6500},
    {"name": "J.T. Poston", "salary": 6500},
    {"name": "Nick Taylor", "salary": 6400},
    {"name": "Nicolas Echavarria", "salary": 6400},
    {"name": "Austin Eckroat", "salary": 6400},
    {"name": "Tom Hoge", "salary": 6400},
    {"name": "Davis Riley", "salary": 6400},
    {"name": "Matthieu Pavon", "salary": 6400},
    {"name": "Jhonattan Vegas", "salary": 6300},
    {"name": "Stephan Jaeger", "salary": 6300},
    {"name": "Joe Highsmith", "salary": 6300},
    {"name": "Matthew McCarty", "salary": 6300},
    {"name": "Kevin Yu", "salary": 6300},
    {"name": "Adam Schenk", "salary": 6300},
    {"name": "Thriston Lawrence", "salary": 6200},
    {"name": "Charl Schwartzel", "salary": 6200},
    {"name": "Patton Kizzire", "salary": 6200},
    {"name": "Danny Willett", "salary": 6200},
    {"name": "Brian Campbell", "salary": 6200},
    {"name": "Zach Johnson", "salary": 6200},
    {"name": "Bubba Watson", "salary": 6100},
    {"name": "Jose Luis Ballester", "salary": 6100},
    {"name": "Justin Hastings", "salary": 6100},
    {"name": "Bernhard Langer", "salary": 6100},
    {"name": "Evan Beck", "salary": 6100},
    {"name": "Vijay Singh", "salary": 6100},
    {"name": "Rafael Campos", "salary": 6000},
    {"name": "Hiroshi Tai", "salary": 6000},
    {"name": "Angel Cabrera", "salary": 6000},
    {"name": "Noah Kent", "salary": 6000},
    {"name": "Fred Couples", "salary": 6000},
    {"name": "Mike Weir", "salary": 6000},
    {"name": "Jose Maria Olazabal", "salary": 6000},
]
