import os

# Controls which page is served at /
# Options: "pre-tournament" or "tournament-live"
SITE_MODE = os.environ.get("SITE_MODE", "pre-tournament")

# Google Sheet ID (fill in after creating the sheet)
GOOGLE_SHEET_ID = os.environ.get("GOOGLE_SHEET_ID", "147wIFWr0bmi4bg5s7kC8Zvn38BVJ6Oh9LQUWIiX2NSY")

# Google Sheet leaderboard embed URL (fill in after publishing the sheet)
LEADERBOARD_EMBED_URL = os.environ.get("LEADERBOARD_EMBED_URL", "")

PLAYERS = [
    {"name": "Scottie Scheffler", "salary": 14000},
    {"name": "Rory McIlroy", "salary": 11600},
    {"name": "Bryson DeChambeau", "salary": 10200},
    {"name": "Jon Rahm", "salary": 10000},
    {"name": "Ludvig Aberg", "salary": 9800},
    {"name": "Xander Schauffele", "salary": 9600},
    {"name": "Collin Morikawa", "salary": 9500},
    {"name": "Tommy Fleetwood", "salary": 9300},
    {"name": "Cameron Young", "salary": 9200},
    {"name": "Justin Rose", "salary": 9100},
    {"name": "Patrick Reed", "salary": 9000},
    {"name": "Hideki Matsuyama", "salary": 8900},
    {"name": "Viktor Hovland", "salary": 8800},
    {"name": "Matt Fitzpatrick", "salary": 8700},
    {"name": "Robert MacIntyre", "salary": 8600},
    {"name": "Brooks Koepka", "salary": 8500},
    {"name": "Jordan Spieth", "salary": 8400},
    {"name": "Justin Thomas", "salary": 8300},
    {"name": "Shane Lowry", "salary": 8200},
    {"name": "Tyrrell Hatton", "salary": 8100},
    {"name": "Chris Gotterup", "salary": 8000},
    {"name": "Jake Knapp", "salary": 8000},
    {"name": "Sepp Straka", "salary": 8000},
    {"name": "Patrick Cantlay", "salary": 7900},
    {"name": "Russell Henley", "salary": 7900},
    {"name": "Akshay Bhatia", "salary": 7800},
    {"name": "Si Woo Kim", "salary": 7800},
    {"name": "Min Woo Lee", "salary": 7700},
    {"name": "Corey Conners", "salary": 7700},
    {"name": "Ben Griffin", "salary": 7600},
    {"name": "Nicolai Hojgaard", "salary": 7600},
    {"name": "Jason Day", "salary": 7600},
    {"name": "Cameron Smith", "salary": 7500},
    {"name": "Sungjae Im", "salary": 7500},
    {"name": "Jacob Bridgeman", "salary": 7400},
    {"name": "Sam Burns", "salary": 7400},
    {"name": "Harris English", "salary": 7300},
    {"name": "Max Homa", "salary": 7300},
    {"name": "Marco Penge", "salary": 7300},
    {"name": "Adam Scott", "salary": 7200},
    {"name": "J.J. Spaun", "salary": 7200},
    {"name": "Gary Woodland", "salary": 7200},
    {"name": "Daniel Berger", "salary": 7200},
    {"name": "Maverick McNealy", "salary": 7200},
    {"name": "Wyndham Clark", "salary": 7100},
    {"name": "Ryan Fox", "salary": 7100},
    {"name": "Sergio Garcia", "salary": 7100},
    {"name": "Alex Noren", "salary": 7000},
    {"name": "Dustin Johnson", "salary": 7000},
    {"name": "Keegan Bradley", "salary": 7000},
    {"name": "Tom McKibbin", "salary": 6900},
    {"name": "Rasmus Hojgaard", "salary": 6900},
    {"name": "Harry Hall", "salary": 6900},
    {"name": "Kurt Kitayama", "salary": 6800},
    {"name": "Ryan Gerard", "salary": 6800},
    {"name": "Aaron Rai", "salary": 6800},
    {"name": "Rasmus Neergaard-Petersen", "salary": 6700},
    {"name": "John Keefer", "salary": 6700},
    {"name": "Nicolas Echavarria", "salary": 6700},
    {"name": "Michael Kim", "salary": 6700},
    {"name": "Michael Brennan", "salary": 6600},
    {"name": "Casey Jarvis", "salary": 6600},
    {"name": "Carlos Ortiz", "salary": 6600},
    {"name": "Max Greyserman", "salary": 6600},
    {"name": "Sami Valimaki", "salary": 6500},
    {"name": "Brian Harman", "salary": 6500},
    {"name": "Nick Taylor", "salary": 6500},
    {"name": "Andrew Novak", "salary": 6400},
    {"name": "Sam Stevens", "salary": 6400},
    {"name": "Davis Riley", "salary": 6400},
    {"name": "Kristoffer Reitan", "salary": 6300},
    {"name": "Hao-Tong Li", "salary": 6300},
    {"name": "Charl Schwartzel", "salary": 6300},
    {"name": "Bubba Watson", "salary": 6300},
    {"name": "Zach Johnson", "salary": 6300},
    {"name": "Aldrich Potgieter", "salary": 6200},
    {"name": "Naoyuki Kataoka", "salary": 6200},
    {"name": "Brian Campbell", "salary": 6200},
    {"name": "Danny Willett", "salary": 6200},
    {"name": "Jackson Herrington", "salary": 6200},
    {"name": "Angel Cabrera", "salary": 6100},
    {"name": "Ethan Fang", "salary": 6100},
    {"name": "Brandon Holtz", "salary": 6100},
    {"name": "Fifa Laopakdee", "salary": 6100},
    {"name": "Vijay Singh", "salary": 6100},
    {"name": "Mason Howell", "salary": 6000},
    {"name": "Fred Couples", "salary": 6000},
    {"name": "Mike Weir", "salary": 6000},
    {"name": "Mateo Pulcini", "salary": 6000},
    {"name": "Jose Maria Olazabal", "salary": 6000},
]
